"""Adds meta data table.

Revision ID: 252094e422ab
Revises: 634cf08b2063
Create Date: 2017-10-21 09:58:03.241234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '252094e422ab'
down_revision = '634cf08b2063'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authority_metadata',
    sa.Column('authority_code', sa.String(), nullable=False),
    sa.Column('most_recent', sa.DateTime(timezone=True), nullable=False),
    sa.Column('least_recent', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('authority_code', 'most_recent', 'least_recent', 'data_type')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('authority_metadata')
    # ### end Alembic commands ###
