"""Adds initial gen data table.

Revision ID: 634cf08b2063
Revises:
Create Date: 2017-10-21 08:59:08.318747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '634cf08b2063'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'generation',
        sa.Column('authority_code', sa.String(), nullable=False),
        sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
        sa.Column('fuel_name', sa.String(), nullable=False),
        sa.Column('gen_MW', sa.Integer(), nullable=False),
        sa.Column('frequency', sa.String(), nullable=False),
        sa.Column('market', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('authority_code', 'timestamp', 'fuel_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generation')
    # ### end Alembic commands ###
